[package]
name = "scrabbler"
version = "0.1.0"
edition = "2021"

[dependencies]
fst = "0.4"
tqdm = "0.4.0"
itertools = "0.10.3"
cursive = "0.19"
rand = "0.8.5"
ansi_term = "0.12.1"
toml = "0.8.10"
serde_derive = "1.0.196"
serde = "1.0.196"
